export const homeData = [
  {
    id: 1,
    img: "/images/bello1.jpg",
    price: "2,300",
    typeOfHome: "3 bedroom apartment",
    description: "Around Airport, near Accra mall for Rent",
    location: "Greater,Accra",
  },
  {
    id: 2,
    img: "/images/bello2.jpeg",
    price: "1,300",
    typeOfHome: "1 bedroom apartment",
    description: "Around Kwashiman, Kaneshi for Rent",
    location: "Central Region, Capecoast",
  },
  {
    id: 3,
    img: "/images/bello3.jpg",
    price: "500",
    typeOfHome: "2 bedroom apartment",
    description: "Around Dzorwulu, near Accra mall for Rent",
    location: "Greater,Accra",
  },
  {
    id: 4,
    img: "/images/bello4.jpeg",
    price: "4,000",
    typeOfHome: "2 bedroom apartment",
    description: "Around Abelemkpe, near Dzorwulu for Rent",
    location: "Central Region, Capecoast",
  },
  {
    id: 5,
    img: "/images/bello3.jpg",
    price: "300",
    typeOfHome: "1 bedroom apartment",
    description: "Around Dome, near Achimota for Rent",
    location: "Greater,Accra",
  },
  {
    id: 6,
    img: "/images/bello2.jpeg",
    price: "700",
    typeOfHome: "1 bedroom apartment",
    description: "Around kasoa, near Capecoast road for Rent",
    location: "Central Region,Capecoast",
  },
];
